### ISSUE TITLE
[Resolved] Убрать непонятный символ из поля ввода нового поста

### ISSUE THREAD

**Issue by gigakun** [gigakun/5ocean_site#15]
Можно ли убрать вот это:
![15](https://user-images.githubusercontent.com/4276038/47607746-951e3080-da2c-11e8-9e5e-5ea36b3c8bb7.png)

**Comment by gigakun** [comment]
[master 9acd605] ISSUE-19: Strange symbol was removed

**Comment by gigakun** [comment]
@Rom-5ocean-fly
Сделано. Можно тестить

**Comment by Rom-5ocean-fly** [comment]
Есть! Протестировано!
