### ISSUE TITLE
[Resolved] Сделать так чтобы было легко связаться с админом

### ISSUE THREAD

**Issue by gigakun** [gigakun/5ocean_site#16]
Сделать так чтобы было легко связаться с админом

**Comment by gigakun** [comment]
Добавить пункт в менб форума "Связаться с администратором"

**Comment by Rom-5ocean-fly** [comment]
Не нашёл этот пункт меню!

**Comment by gigakun** [comment]
@Rom-5ocean-fly 
Так я еще не добавил:) Я напишу когда добавлю.

**Comment by gigakun** [comment]
@Rom-5ocean-fly 
Сделано. Можно тестить.

**Comment by Rom-5ocean-fly** [comment]
Можно сместить эту кнопку связи в правый край?

**Comment by gigakun** [comment]
@Rom-5ocean-fly 
так?
![image](https://user-images.githubusercontent.com/4276038/47702377-c580ed00-dc2d-11e8-9435-99c23bf56074.png)
![image](https://user-images.githubusercontent.com/4276038/47702429-efd2aa80-dc2d-11e8-8aef-f3d228fa824e.png)

**Comment by gigakun** [comment]
Если да то сделаю позже.

**Comment by Rom-5ocean-fly** [comment]
Да, именно так.

**Comment by gigakun** [comment]
[master 14da5b8] ISSUE-16: Add contact administrator item in top  menu bar

**Comment by gigakun** [comment]
@Rom-5ocean-fly 
Готово. Можно тестить

**Comment by Rom-5ocean-fly** [comment]
Есть! Протестировано
