### ISSUE TITLE
Сделать проверку логина на корректность

### ISSUE THREAD

**Issue by gigakun** [gigakun/5ocean_site#17]
При вводе логина нужно проверять его на соответствие разрешенным символам

**Comment by Rom-5ocean-fly** [comment]
Проверено.

**Comment by gigakun** [comment]
бага была создана на основе репорта Максима о том что имя пользователя не соответствует nice name. Например логин vasya.pupkin будет преобразован в @vasya-pupkin. Это ни каким образом не влияет на функционал. Так так отображение nicename было отключено то я думаю введение дополнительных ограничений на формат имени не нужно.
