### ISSUE TITLE
[Resolved] Создается несколько постов при многократном нажатии на кнопку "Добавить ответ"

### ISSUE THREAD

**Issue by gigakun** [gigakun/5ocean_site#18]
Создается несколько постов при многократном нажатии на кнопку "Добавить ответ"
![untitled](https://user-images.githubusercontent.com/4276038/47612557-0e01a480-da8e-11e8-9036-a6083b2ca826.png)

**Comment by gigakun** [comment]
[master 0f4c5a1] ISSUE-18: Avoid posting several messages by clicking on add reply button

**Comment by gigakun** [comment]
@Rom-5ocean-fly 
Готово. Можно тестить.

После нажатия на кнопку она исчезает и появляется спиннер. Нажать повторно на кнопку нельзя так как она скрыта. Это позволяет дождаться корректной отправки формы и перезагрузки страницы.

**Comment by gigakun** [comment]
Как выглядит спиннер
![image](https://user-images.githubusercontent.com/4276038/47751667-7d041680-dca3-11e8-848d-d1d570428d21.png)

**Comment by Rom-5ocean-fly** [comment]
Кнопка после однократного нажатия исчезает. Так что множественный ответ невозможен.

**Comment by Rom-5ocean-fly** [comment]
Есть! Протестировано!
