### ISSUE TITLE
[Resolved] Убрать строчку под аватаркой в сообщениях.

### ISSUE THREAD

**Issue by Rom-5ocean-fly** [gigakun/5ocean_site#19]
![_](https://user-images.githubusercontent.com/44565857/47644819-44b7e780-db80-11e8-857d-527fc041b931.JPG)

Выделенное жёлтым лучше убрать - мешает восприятию.

**Comment by gigakun** [comment]
@Rom-5ocean-fly 
Можно тестить

**Comment by gigakun** [comment]
@Rom-5ocean-fly
Ошибся. Эта будет готова позже.

**Comment by gigakun** [comment]
@Rom-5ocean-fly 
Я бы кстати оставил это так как это дает возможность отправлять письмо тем кто упомянут в посте. Штука нужная. Подтверди что это действительно необходимо.

**Comment by Rom-5ocean-fly** [comment]
Да, необходимо!

**Comment by gigakun** [comment]
[master 615af7e] ISSUE-19: Remove nicename from author info in post. @gigakun for example

**Comment by gigakun** [comment]
@Rom-5ocean-fly 
Сделано. Можно тестить.

**Comment by Rom-5ocean-fly** [comment]
Есть!
