### ISSUE TITLE
[Resolved] Убрать подтверждение email из регистрации пользователей

### ISSUE THREAD

**Issue by gigakun** [gigakun/5ocean_site#20]
Убрать подтверждение email из регистрации пользователей

**Comment by gigakun** [comment]
@Rom-5ocean-fly
Можно тестить

**Comment by Rom-5ocean-fly** [comment]
После регистрации пользователя, он должен сразу попадать не в профиль, а на главную страницу форума.

**Comment by gigakun** [comment]
@Rom-5ocean-fly  
Я так понял функционал протестирован можно закрывать?

**Comment by Rom-5ocean-fly** [comment]
Да. Создам новый кейс.
