### ISSUE TITLE
Отображение имён админа красным.

### ISSUE THREAD

**Issue by Rom-5ocean-fly** [gigakun/5ocean_site#24]
Прошу убрать отображение имени админа под аватаркой красным.
Цвет имени нужно сделать такой же, как у остальных пользователей.

**Comment by gigakun** [comment]
В настройках групп пользователей изменены цвета групп.
Для гостей черный цвет
Для всех остальных #3f7796:![image](https://user-images.githubusercontent.com/4276038/47801814-010bdc00-dd40-11e8-9fbe-03cf638cc9b7.png)

**Comment by gigakun** [comment]
@Rom-5ocean-fly 
Можешь проверять

**Comment by Rom-5ocean-fly** [comment]
Проверено!
